name: example
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_comics_ui:
    path: ../
  flutter_web_plugins:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/fonts/

  fonts:
    - family: vazir
      fonts:
        - asset: assets/fonts/vazir/Vazir-Bold.ttf
        - asset: assets/fonts/vazir/Vazir-Light.ttf
        - asset: assets/fonts/vazir/Vazir-Medium.ttf
        - asset: assets/fonts/vazir/Vazir-Thin.ttf
        - asset: assets/fonts/vazir/Vazir.ttf
    - family: integral-cf
      fonts:
        - asset: assets/fonts/integral-cf/IntegralCF-Bold.otf
        - asset: assets/fonts/integral-cf/IntegralCF-BoldOblique.otf
        - asset: assets/fonts/integral-cf/IntegralCF-DemiBold.otf
        - asset: assets/fonts/integral-cf/IntegralCF-DemiBoldOblique.otf
        - asset: assets/fonts/integral-cf/IntegralCF-ExtraBold.otf
        - asset: assets/fonts/integral-cf/IntegralCF-ExtraBoldOblique.otf
        - asset: assets/fonts/integral-cf/IntegralCF-Heavy.otf
        - asset: assets/fonts/integral-cf/IntegralCF-HeavyOblique.otf
        - asset: assets/fonts/integral-cf/IntegralCF-Medium.otf
        - asset: assets/fonts/integral-cf/IntegralCF-MediumOblique.otf
        - asset: assets/fonts/integral-cf/IntegralCF-Regular.otf
        - asset: assets/fonts/integral-cf/IntegralCF-RegularOblique.otf