name: flutter_comics_ui
description: Comics UI Widgets 
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: com.comics.ui
        pluginClass: ComicsUI
      ios:
        pluginClass: ComicsUI
      web:
        pluginClass: ComicsUI
      linux:
        pluginClass: ComicsUI
      macos:
        pluginClass: ComicsUI
      windows:
        pluginClass: ComicsUI

  assets:
    - assets/fonts/

  fonts:
    - family: vazir
      fonts:
        - asset: assets/fonts/vazir/Vazir-Bold.ttf
        - asset: assets/fonts/vazir/Vazir-Light.ttf
        - asset: assets/fonts/vazir/Vazir-Medium.ttf
        - asset: assets/fonts/vazir/Vazir-Thin.ttf
        - asset: assets/fonts/vazir/Vazir.ttf
    - family: integral-cf
      fonts:
        - asset: assets/fonts/integral-cf/IntegralCF-Bold.otf
        - asset: assets/fonts/integral-cf/IntegralCF-BoldOblique.otf
        - asset: assets/fonts/integral-cf/IntegralCF-DemiBold.otf
        - asset: assets/fonts/integral-cf/IntegralCF-DemiBoldOblique.otf
        - asset: assets/fonts/integral-cf/IntegralCF-ExtraBold.otf
        - asset: assets/fonts/integral-cf/IntegralCF-ExtraBoldOblique.otf
        - asset: assets/fonts/integral-cf/IntegralCF-Heavy.otf
        - asset: assets/fonts/integral-cf/IntegralCF-HeavyOblique.otf
        - asset: assets/fonts/integral-cf/IntegralCF-Medium.otf
        - asset: assets/fonts/integral-cf/IntegralCF-MediumOblique.otf
        - asset: assets/fonts/integral-cf/IntegralCF-Regular.otf
        - asset: assets/fonts/integral-cf/IntegralCF-RegularOblique.otf
