name: flutter_comics_ui
description: Implements Comics UI Widgets in Flutter. A free Flutter Comical UI Kit.
version: 0.0.1
homepage: https://github.com/Asncodes-80/flutter-comics-ui

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true