# Build Flutter web app and deploy as gh-pages
name: GH-Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Install deps
        run: flutter pub get
        working-directory: ./example

      - name: Build Flutter web app
        run: flutter build web --release --source-maps
        working-directory: ./example

      - name: Deploy
        run: |
          cd example/build/web
          git init
          git config user.name "Asncodes-80"
          git config user.email "asn80.asn@hotmail.com"
          git remote add secure-origin https://username:${GITHUB_TOKEN}@github.com/flutter-comics-ui.git
          git checkout -b gh-pages
          git add .
          git commit -m "ci(gh-pages): update and deploy web app"
          git push --force secure-origin gh-pages